name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

    - name: Build Docker Image
      run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/theerachai2530/django-cicd-test:latest

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/theerachai2530/django-cicd-test:latest

