name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'  # ระบุเวอร์ชัน Java ถ้าจำเป็น

      - name: Build with Maven
        run: mvn clean install  # ปรับคำสั่งนี้ตามเครื่องมือสร้างของคุณ

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.1.0  # ใช้เวอร์ชันล่าสุด
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # โทเค็น GitHub สำหรับข้อมูล PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     # โทเค็น SonarCloud
        with:
          args: >
            -Dsonar.projectKey=my-project-key          # แทนที่ด้วย project key ของคุณ
            -Dsonar.organization=my-organization        # แทนที่ด้วย organization key ของคุณ
            -Dsonar.sources=src                         # ปรับไดเรกทอรีแหล่งที่มาตามต้องการ
            -Dsonar.tests=src/test                      # ปรับไดเรกทอรีการทดสอบตามต้องการ
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info  # สำหรับโปรเจกต์ JavaScript
